[workspace]
members = [
    "xtask"
]

[package]
name = "maknuuner"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = { version = "1.0.104", default-features = false }
caseless = { version = "0.2.2", default-features = false }
compact_str = { version = "0.10.0", features = ["serde"], default-features = false }
csv = { version = "1.4.0", default-features = false }
either = { version = "1.17.0", default-features = false }
interner = { version = "0.2.1", default-features = false }
itertools = { version = "0.15.0", default-features = false }
ordered-float = { version = "5.3.0", default-features = false }
serde = { version = "1.0.229", default-features = false }
smallvec = { version = "1.15.2", default-features = false, features = ["union"] }
tokio = { version = "1.53.1", features = ["macros", "rt-multi-thread"], default-features = false }
topcoat = { version = "0.5.0", default-features = false, features = ["asset", "discover", "font", "runtime", "serve", "view"] }
unicode-normalization = { version = "0.1.25", default-features = false }
